random_state: 42

data:
  kind: synthetic
  test_size: 0.2
  n_samples: 3000
  n_features: 20
  n_informative: 6
  n_redundant: 3
  weights: [0.95, 0.05]
  target: target

validation:
  cv:
    n_splits: 5
    n_repeats: 2

models:
  - name: logistic_l2
    type: logistic
    params:
      C: 1.0
      class_weight: balanced
      solver: lbfgs
  - name: rf_200
    type: rf
    params:
      n_estimators: 200
      max_depth: 8
      class_weight: balanced
  - name: hgb
    type: hist_gbdt
    params:
      max_depth: 6
      max_iter: 150

calibration:
  method: sigmoid

cost:
  fn: 10.0
  fp: 1.0

reports:
  pr_k: 100

paths:
  artifacts_dir: artifacts
