random_state: 1337

data:
  kind: synthetic
  test_size: 0.25
  n_samples: 5000
  n_features: 25
  n_informative: 7
  n_redundant: 4
  n_repeated: 0
  weights: [0.98, 0.02]
  target: target

validation:
  cv:
    n_splits: 5
    n_repeats: 3

models:
  - name: logistic_balanced
    type: logistic
    params:
      C: 0.5
      class_weight: balanced
      solver: lbfgs
      max_iter: 500
  - name: rf_strong
    type: rf
    params:
      n_estimators: 400
      max_depth: 10
      min_samples_leaf: 2
      class_weight: balanced
  - name: hgb_fast
    type: hist_gbdt
    params:
      max_depth: 6
      max_iter: 200

calibration:
  method: isotonic

cost:
  fn: 20.0
  fp: 1.0

reports:
  pr_k: 200

paths:
  artifacts_dir: artifacts
